# ssl配置
# https加密端口号 443
# 服务器运行端口
server:
  port: 443
  # SSL证书路径 一定要加上classpath，证书名只能有一个后缀，否则找不到不到文件
  ssl:
    key-store: classpath:xxxxxx.pfx     #您：需要修改
    # SSL证书密码
    key-store-password: xxxxxx          #您：需要修改
    enabled: true
    # 证书类型
    key-store-type: PKCS12

# 设置：映射到443的端口
myHttp: 80

# 设置：数据源
spring:
  thymeleaf:
    cache: false  # 设置：thymeleaf 缓存为false, 这样修改之后马上生效，便于调试
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 连接驱动：Java连接mysql数据库
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: xxxxxx  #您：需要修改

# 配置：mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml    # 设置：接口绑定mapper路径
  type-aliases-package: com.lw.pojo	      # 设置：实体类别名

# 配置pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 配置日志输出
logging:
  level:
    root: warn
    com.star: info
  file:
    path: log/blog-pro.log
